### ISSUE TITLE
Low performance in semantic textual similarity task

### ISSUE THREAD

**Issue by emrecncelik** [spacyturk/spacyturk#1]
Hello,

First of all. thank you for training and sharing such a great model for Turkish.

I am trying to use floret for the semantic similarity task, but I am getting bad results. I wondered if I was making a mistake or if the model is not suitable (I thought it should be) for this task.

So here's my code, I am evaluating the model on semantic textual similarity benchmark dataset for Turkish.

```python
import spacy
import spacyturk

from datasets import load_dataset

spacyturk.download("tr_floret_web_lg")

nlp = spacy.load("tr_floret_web_lg")
dataset = load_dataset("emrecan/stsb-mt-turkish")

similarities = []
for s1, s2 in zip(dataset["test"]['sentence1'], dataset["test"]['sentence2']):
    similarities.append(nlp(s1).similarity(nlp(s2)))

pearsonr(similarities, dataset["test"]["score"])
```
Correlation coefficient I am getting as the result is: 0.24. When I replace the model with `spacy.blank("tr")` the result is 0.16.

I expected it to be over 0.70 since floret is almost as good as fasttext in many cases. Do you have any ideas why this could occur? Also, could you also provide bin files for the models so I can test them by isolating from the spacy pipeline (or any file compatible with `floret.load_model`)?

Thank you.

**Comment by bediiaydogan** [comment]
Hello,

Did you try the same task with fastText’s pretrained vectors? They were trained on a larger corpus and may be give better results.  And I couldn’t understand how you can get vectors from a blank spacy model. 

If you share your email address, I will send you a download link for bin files.

Thanks for your contribution.

**Comment by emrecncelik** [comment]
I do not know how a blank model finds similarities internally either, but my point was to show that floret's results were unexpectedly low.

Here's the results for different models:

Common Crawl FastText (https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.tr.300.bin.gz):  0.49670839741466066
Wiki FastText (https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.tr.zip): 0.493453591834952
SentenceBERT (emrecan/bert-base-turkish-cased-mean-nli-stsb-tr) : 0.8343865299982284

I guess expecting 0.7 was too optimistic, but still I expected floret to have similar performance to FastText. Also, I think Wiki FastText has a smaller corpus than the floret model.

My email is emrecncelik@gmail.com, thanks in advance.

**Comment by bediiaydogan** [comment]
Spacy calculates sentence vectors as the mean of token vectors and actually they are not good for sentence representation. Did you use the same methodology for fastText vectors? Unfortunately, I'm on vacation now and will be able to send the download link next week. Please let me know if you achive any improvements.

**Comment by bediiaydogan** [comment]
I just got a look at your test dataset and want to share some of my observations.

First of all let me identify how you get scores from a blank spacy model. Blank spacy models return similarity scores as 1.0 for the exact match and 0.0 for the others. In your test dataset 15 of the samples have exactly the same sentences (indices are 136, 251, 411, 437, 566, 623, 631, 664, 674, 692, 737, 773, 788, 829, 854) and you get scores as 1.0 for these samples and 0.0 for the remaining. Although there are no sentence vectors available, you can still get similarity scores as either 0.0 or 1.0.

In the dataset, majority of the samples have sentences in which only one of the tokens differs. Spacy calculates sentence vectors as the average of token vectors. Therefore, a single token vector has minor effect on the sentence vector calculation.  Let me explain this issue with an example from the dataset;

```
nlp = spacy.load("tr_floret_web_lg")

# test dataset index = 7, score = 2.2
s1 = "Bir adam davul çalıyor."
s2 = "Bir adam gitar çalıyor."

# prints 0.983
print(nlp(s1).similarity(nlp(s2)))

# prints 0.679
print(nlp("davul").similarity(nlp("gitar")))
```
In the above sample, only one token is different and the remaining 4 tokens are exactly the same. The STS score is 2.2, but a high sentence similarity score is found (0.983). Similarity score for "davul" and "gitar" tokens is 0.679. This is the expected result because both are music instruments and probably had similar contexts during training. Let's replace "gitar" with a token completely dissimilar with "davul" and see the results.  

```
s1 = "Bir adam davul çalıyor."
s2 = "Bir adam para çalıyor."

# prints 0.903
print(nlp(s1).similarity(nlp(s2)))

# prints 0.109
print(nlp("davul").similarity(nlp("para")))
```
Altough "davul" and "para" tokens are completely dissimilar, we still get a high sentence similarity score (0.903). Because 4 out of 5 tokens are exactly the same and these tokens' vectors dominate the sentence vector calculation.
